try:
  n = m
#except IOError as err:
except Exception as e:
    print(f"{e}")

print('####################')
